import { PrismaClient, ProductType, Category } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Début du seeding...')

  // Nettoyer la base
  await prisma.statusHistory.deleteMany()
  await prisma.orderItem.deleteMany()
  await prisma.order.deleteMany()
  await prisma.review.deleteMany()
  await prisma.product.deleteMany()
  await prisma.brand.deleteMany()
  await prisma.admin.deleteMany()
  await prisma.siteSettings.deleteMany()
  await prisma.promoBanner.deleteMany()

  // Créer l'admin
  const hashedPassword = await bcrypt.hash('OudRoyal2024!', 12)
  await prisma.admin.create({
    data: {
      email: 'admin@oudroyal.ma',
      password: hashedPassword,
      name: 'Admin OUD ROYAL',
      role: 'SUPER_ADMIN',
    },
  })
  console.log('✅ Admin créé')

  // Créer les marques
  const lattafa = await prisma.brand.create({
    data: {
      name: 'Lattafa',
      slug: 'lattafa',
      description: 'Maison de parfumerie émiratie reconnue pour ses créations orientales luxueuses à prix accessibles.',
      country: 'Émirats Arabes Unis',
    },
  })

  const alhambra = await prisma.brand.create({
    data: {
      name: 'Maison Alhambra',
      slug: 'maison-alhambra',
      description: 'Marque premium spécialisée dans les parfums orientaux inspirés des plus grandes maisons.',
      country: 'Émirats Arabes Unis',
    },
  })

  const frenchAvenue = await prisma.brand.create({
    data: {
      name: 'French Avenue',
      slug: 'french-avenue',
      description: 'Fusion parfaite entre élégance française et richesse orientale.',
      country: 'Émirats Arabes Unis',
    },
  })

  const fragranceWorld = await prisma.brand.create({
    data: {
      name: 'Fragrance World',
      slug: 'fragrance-world',
      description: 'Leader mondial des parfums orientaux avec un catalogue riche et varié.',
      country: 'Émirats Arabes Unis',
    },
  })
  console.log('✅ 4 marques créées')

  // Créer les produits
  const products = [
    {
      name: 'Bade\'e Al Oud Amethyst',
      slug: 'badee-al-oud-amethyst',
      description: 'Un parfum oriental envoûtant qui mêle des notes de fruits rouges, de rose et de musc. Une fragrance captivante pour les soirées élégantes.',
      price: 299,
      oldPrice: 399,
      volume: '100ml',
      type: ProductType.EAU_DE_PARFUM,
      category: Category.UNISEX,
      image: '/images/products/placeholder-1.jpg',
      images: [],
      notesTop: ['Safran', 'Fruits rouges', 'Bergamote'],
      notesMiddle: ['Rose', 'Jasmin', 'Oud'],
      notesBase: ['Musc', 'Ambre', 'Vanille'],
      rating: 4.8,
      reviewCount: 124,
      stock: 50,
      sold: 230,
      isFeatured: true,
      isNew: false,
      isBestSeller: true,
      brandId: lattafa.id,
    },
    {
      name: 'Raghba',
      slug: 'raghba',
      description: 'Raghba est un parfum gourmand et oriental, offrant un mélange délicieux de vanille, de musc blanc et de bois de santal.',
      price: 199,
      oldPrice: 279,
      volume: '100ml',
      type: ProductType.EAU_DE_PARFUM,
      category: Category.UNISEX,
      image: '/images/products/placeholder-2.jpg',
      images: [],
      notesTop: ['Cannelle', 'Muscade', 'Lavande'],
      notesMiddle: ['Vanille', 'Musc blanc', 'Iris'],
      notesBase: ['Santal', 'Cèdre', 'Ambre gris'],
      rating: 4.6,
      reviewCount: 89,
      stock: 75,
      sold: 180,
      isFeatured: true,
      isNew: false,
      isBestSeller: true,
      brandId: lattafa.id,
    },
    {
      name: 'Asad',
      slug: 'asad',
      description: 'Asad incarne la puissance et le raffinement. Un parfum boisé et ambré qui laisse une empreinte inoubliable.',
      price: 349,
      oldPrice: 449,
      volume: '100ml',
      type: ProductType.EAU_DE_PARFUM,
      category: Category.HOMME,
      image: '/images/products/placeholder-3.jpg',
      images: [],
      notesTop: ['Poivre noir', 'Ananas', 'Gingembre'],
      notesMiddle: ['Oud', 'Tabac', 'Iris'],
      notesBase: ['Ambre', 'Vanille', 'Benjoin'],
      rating: 4.9,
      reviewCount: 156,
      stock: 40,
      sold: 310,
      isFeatured: true,
      isNew: false,
      isBestSeller: true,
      brandId: lattafa.id,
    },
    {
      name: 'Khamrah',
      slug: 'khamrah',
      description: 'Un chef-d\'œuvre gourmand inspiré des soirées orientales. Notes de cognac, vanille et bois précieux.',
      price: 379,
      oldPrice: 499,
      volume: '100ml',
      type: ProductType.EAU_DE_PARFUM,
      category: Category.UNISEX,
      image: '/images/products/placeholder-4.jpg',
      images: [],
      notesTop: ['Cannelle', 'Bergamote', 'Noix de muscade'],
      notesMiddle: ['Datte', 'Praline', 'Tubéreuse'],
      notesBase: ['Vanille', 'Tabac', 'Benjoin'],
      rating: 4.9,
      reviewCount: 203,
      stock: 30,
      sold: 420,
      isFeatured: true,
      isNew: true,
      isBestSeller: true,
      brandId: lattafa.id,
    },
    {
      name: 'Jean Lowe Immortal',
      slug: 'jean-lowe-immortal',
      description: 'Une interprétation orientale audacieuse. Un parfum magnétique alliant fraîcheur et profondeur.',
      price: 259,
      oldPrice: 349,
      volume: '100ml',
      type: ProductType.EAU_DE_PARFUM,
      category: Category.HOMME,
      image: '/images/products/placeholder-5.jpg',
      images: [],
      notesTop: ['Lavande', 'Menthe', 'Citron'],
      notesMiddle: ['Géranium', 'Fève tonka', 'Coumarine'],
      notesBase: ['Vanille', 'Santal', 'Musc'],
      rating: 4.5,
      reviewCount: 67,
      stock: 60,
      sold: 145,
      isFeatured: false,
      isNew: true,
      isBestSeller: false,
      brandId: alhambra.id,
    },
    {
      name: 'Toscano Leather',
      slug: 'toscano-leather',
      description: 'Un cuir italien revisité à l\'orientale. Élégance pure et caractère affirmé.',
      price: 289,
      oldPrice: 389,
      volume: '80ml',
      type: ProductType.EAU_DE_PARFUM,
      category: Category.HOMME,
      image: '/images/products/placeholder-6.jpg',
      images: [],
      notesTop: ['Cardamome', 'Poivre rose', 'Mandarine'],
      notesMiddle: ['Cuir', 'Jasmin', 'Cèdre'],
      notesBase: ['Oud', 'Musc', 'Patchouli'],
      rating: 4.7,
      reviewCount: 45,
      stock: 55,
      sold: 98,
      isFeatured: true,
      isNew: false,
      isBestSeller: false,
      brandId: alhambra.id,
    },
    {
      name: 'Musc Royale',
      slug: 'musc-royale',
      description: 'La quintessence du musc oriental. Doux, enveloppant et infiniment séduisant.',
      price: 229,
      oldPrice: null,
      volume: '100ml',
      type: ProductType.EAU_DE_PARFUM,
      category: Category.FEMME,
      image: '/images/products/placeholder-7.jpg',
      images: [],
      notesTop: ['Rose', 'Framboise', 'Bergamote'],
      notesMiddle: ['Musc blanc', 'Pivoine', 'Magnolia'],
      notesBase: ['Bois de cachemire', 'Ambre', 'Vanille'],
      rating: 4.4,
      reviewCount: 34,
      stock: 80,
      sold: 67,
      isFeatured: false,
      isNew: true,
      isBestSeller: false,
      brandId: alhambra.id,
    },
    {
      name: 'Arabesque',
      slug: 'arabesque',
      description: 'Un voyage olfactif au cœur des souks d\'Orient. Riche, complexe et absolument divin.',
      price: 319,
      oldPrice: 429,
      volume: '100ml',
      type: ProductType.EXTRAIT_DE_PARFUM,
      category: Category.UNISEX,
      image: '/images/products/placeholder-8.jpg',
      images: [],
      notesTop: ['Encens', 'Safran', 'Poivre noir'],
      notesMiddle: ['Oud', 'Rose de Damas', 'Patchouli'],
      notesBase: ['Ambre gris', 'Musc', 'Bois de santal'],
      rating: 4.8,
      reviewCount: 78,
      stock: 35,
      sold: 156,
      isFeatured: true,
      isNew: false,
      isBestSeller: true,
      brandId: alhambra.id,
    },
    {
      name: 'Le Parfum Royal',
      slug: 'le-parfum-royal',
      description: 'L\'alliance parfaite entre la haute parfumerie française et les ingrédients nobles d\'Orient.',
      price: 399,
      oldPrice: 549,
      volume: '100ml',
      type: ProductType.EXTRAIT_DE_PARFUM,
      category: Category.FEMME,
      image: '/images/products/placeholder-9.jpg',
      images: [],
      notesTop: ['Rose centifolia', 'Poivre rose', 'Litchi'],
      notesMiddle: ['Oud', 'Jasmin sambac', 'Pivoine'],
      notesBase: ['Musc blanc', 'Santal', 'Praline'],
      rating: 4.7,
      reviewCount: 56,
      stock: 25,
      sold: 112,
      isFeatured: true,
      isNew: true,
      isBestSeller: false,
      brandId: frenchAvenue.id,
    },
    {
      name: 'Noir Absolu',
      slug: 'noir-absolu',
      description: 'Mystérieux et envoûtant. Un parfum sombre qui révèle une personnalité intense.',
      price: 359,
      oldPrice: 459,
      volume: '80ml',
      type: ProductType.EAU_DE_PARFUM,
      category: Category.HOMME,
      image: '/images/products/placeholder-10.jpg',
      images: [],
      notesTop: ['Bergamote', 'Absinthe', 'Cardamome'],
      notesMiddle: ['Cuir', 'Oud', 'Fève tonka'],
      notesBase: ['Ambre noir', 'Vanille', 'Vétiver'],
      rating: 4.6,
      reviewCount: 41,
      stock: 45,
      sold: 89,
      isFeatured: false,
      isNew: false,
      isBestSeller: false,
      brandId: frenchAvenue.id,
    },
    {
      name: 'Elegance Oud',
      slug: 'elegance-oud',
      description: 'La sophistication à l\'état pur. Un oud élégant et raffiné, parfait pour toutes les occasions.',
      price: 279,
      oldPrice: 379,
      volume: '100ml',
      type: ProductType.EAU_DE_PARFUM,
      category: Category.UNISEX,
      image: '/images/products/placeholder-11.jpg',
      images: [],
      notesTop: ['Citron de Sicile', 'Cardamome', 'Safran'],
      notesMiddle: ['Oud', 'Rose', 'Géranium'],
      notesBase: ['Santal', 'Musc', 'Cèdre'],
      rating: 4.5,
      reviewCount: 52,
      stock: 65,
      sold: 134,
      isFeatured: false,
      isNew: false,
      isBestSeller: true,
      brandId: frenchAvenue.id,
    },
    {
      name: 'Fleur de Nuit',
      slug: 'fleur-de-nuit',
      description: 'Un bouquet floral nocturne, sensuel et captivant. Pour les femmes qui osent.',
      price: 249,
      oldPrice: null,
      volume: '100ml',
      type: ProductType.EAU_DE_PARFUM,
      category: Category.FEMME,
      image: '/images/products/placeholder-12.jpg',
      images: [],
      notesTop: ['Tubéreuse', 'Ylang-ylang', 'Poire'],
      notesMiddle: ['Jasmin', 'Gardénia', 'Orchidée'],
      notesBase: ['Musc', 'Vanille', 'Bois de cèdre'],
      rating: 4.3,
      reviewCount: 29,
      stock: 70,
      sold: 56,
      isFeatured: false,
      isNew: true,
      isBestSeller: false,
      brandId: frenchAvenue.id,
    },
    {
      name: 'Sultan Al Quloob',
      slug: 'sultan-al-quloob',
      description: 'Le sultan des cœurs. Un parfum royal qui impose le respect et l\'admiration.',
      price: 329,
      oldPrice: 449,
      volume: '100ml',
      type: ProductType.EXTRAIT_DE_PARFUM,
      category: Category.HOMME,
      image: '/images/products/placeholder-13.jpg',
      images: [],
      notesTop: ['Encens oliban', 'Poivre noir', 'Gingembre'],
      notesMiddle: ['Oud cambodgien', 'Cuir', 'Ambre'],
      notesBase: ['Musc noir', 'Santal', 'Civette'],
      rating: 4.8,
      reviewCount: 91,
      stock: 30,
      sold: 198,
      isFeatured: true,
      isNew: false,
      isBestSeller: true,
      brandId: fragranceWorld.id,
    },
    {
      name: 'Oud Mood',
      slug: 'oud-mood',
      description: 'Capture l\'essence même de l\'oud dans sa forme la plus pure et la plus intense.',
      price: 269,
      oldPrice: 359,
      volume: '100ml',
      type: ProductType.EAU_DE_PARFUM,
      category: Category.UNISEX,
      image: '/images/products/placeholder-14.jpg',
      images: [],
      notesTop: ['Safran', 'Cannelle', 'Citron vert'],
      notesMiddle: ['Oud', 'Rose de Taif', 'Cèdre'],
      notesBase: ['Ambre', 'Musc', 'Vanille bourbon'],
      rating: 4.6,
      reviewCount: 73,
      stock: 50,
      sold: 167,
      isFeatured: false,
      isNew: false,
      isBestSeller: true,
      brandId: fragranceWorld.id,
    },
    {
      name: 'Midnight Oud',
      slug: 'midnight-oud',
      description: 'Les mystères de minuit capturés dans un flacon. Sombre, profond, irrésistible.',
      price: 299,
      oldPrice: 399,
      volume: '80ml',
      type: ProductType.EAU_DE_PARFUM,
      category: Category.UNISEX,
      image: '/images/products/placeholder-15.jpg',
      images: [],
      notesTop: ['Bergamote', 'Safran', 'Cumin'],
      notesMiddle: ['Oud', 'Rose bulgare', 'Cypriol'],
      notesBase: ['Musc noir', 'Ambre', 'Patchouli'],
      rating: 4.7,
      reviewCount: 64,
      stock: 40,
      sold: 143,
      isFeatured: true,
      isNew: true,
      isBestSeller: false,
      brandId: fragranceWorld.id,
    },
    {
      name: 'Velvet Rose',
      slug: 'velvet-rose',
      description: 'La douceur du velours mariée à l\'intensité de la rose. Un classique oriental réinventé.',
      price: 219,
      oldPrice: 299,
      volume: '100ml',
      type: ProductType.EAU_DE_PARFUM,
      category: Category.FEMME,
      image: '/images/products/placeholder-16.jpg',
      images: [],
      notesTop: ['Rose de Damas', 'Framboise', 'Bergamote'],
      notesMiddle: ['Oud', 'Jasmin', 'Pivoine'],
      notesBase: ['Musc', 'Vanille', 'Santal'],
      rating: 4.5,
      reviewCount: 48,
      stock: 60,
      sold: 95,
      isFeatured: false,
      isNew: false,
      isBestSeller: false,
      brandId: fragranceWorld.id,
    },
  ]

  for (const product of products) {
    await prisma.product.create({ data: product })
  }
  console.log('✅ 16 produits créés')

  // Paramètres du site
  await prisma.siteSettings.create({
    data: {
      siteName: 'OUD ROYAL',
      phone: '+212 6 00 00 00 00',
      email: 'contact@oudroyal.ma',
      whatsapp: '+212600000000',
      freeShippingThreshold: 500,
      standardShipping: 35,
      currency: 'DH',
    },
  })
  console.log('✅ Paramètres du site créés')

  console.log('🎉 Seeding terminé avec succès !')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })